version: '3'
services:  
  user-service:
    build: ./user-service
    ports:
      - '8080:8080'
    depends_on:
      - mongo-ehr
  case-service:
      build: ./case-service
      ports:
        - '8081:8081'
      depends_on:
        - mongo-ehr
  ui-service:
        build: ./ui
        ports:
          - '80:80'
        depends_on:
          - user-service
          - case-service          
  mongo-ehr:
    image: mongo
    ports:
      - '27017:27017'
