version: '3'
services:  
  api:
    build: ./server
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  api:
      build: ./case-service
      ports:
        - '8081:8081'
      depends_on:
        - mongo    
  mongo:
    image: mongo
    ports:
      - '27017:27017'
